import Foundation
import Logging

struct VideoMetadata: Sendable {
    let title: String
    let channel: String
    let description: String
    let durationSeconds: Int

    var formattedDuration: String {
        let hours = durationSeconds / 3600
        let minutes = (durationSeconds % 3600) / 60
        let seconds = durationSeconds % 60
        if hours > 0 {
            return "\(hours):\(String(format: "%02d", minutes)):\(String(format: "%02d", seconds))"
        }
        return "\(minutes):\(String(format: "%02d", seconds))"
    }
}

struct CaptionTrack: Sendable {
    let baseURL: String
    let languageCode: String
    let languageName: String
    let isAutoGenerated: Bool
}

struct TranscriptEntry: Sendable {
    let start: Double
    let duration: Double
    let text: String
}

struct TranscriptResult: Sendable {
    let metadata: VideoMetadata
    let entries: [TranscriptEntry]
    let languageCode: String
}

struct CaptionTrackResult: Sendable {
    let metadata: VideoMetadata
    let tracks: [CaptionTrack]
}

enum TranscriptFetcher {

    private static let logger = Logger(label: "yt_transcript_mcp.fetcher")

    private static let userAgent =
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

    // InnerTube API endpoint (Android client avoids PO token requirement)
    private static let innertubeAPIURL = "https://www.youtube.com/youtubei/v1/player?key="

    // Compiled once; pattern is a constant so try! is safe (same approach as VideoIDExtractor).
    private static let apiKeyPattern = try! NSRegularExpression(
        pattern: #""INNERTUBE_API_KEY":\s*"([a-zA-Z0-9_-]+)""#
    )

    // YouTube Android client version for InnerTube API requests.
    // YouTube periodically enforces minimum versions. If the API starts
    // returning errors, try updating this to a recent version number.
    // Last verified: 2026-03
    private static let androidClientVersion = "20.10.38"

    // MARK: - Public API

    /// Fetches available caption tracks and video metadata for a video.
    static func fetchCaptionTracks(videoID: String) async throws -> CaptionTrackResult {
        let innertubeData = try await fetchInnertubeData(videoID: videoID)
        let metadata = extractMetadata(from: innertubeData, videoID: videoID)
        let renderer = try extractCaptionsRenderer(from: innertubeData, videoID: videoID)
        let tracks = try extractCaptionTracks(from: renderer, videoID: videoID)
        return CaptionTrackResult(metadata: metadata, tracks: tracks)
    }

    /// Fetches the transcript for a video, optionally in a specific language.
    /// Falls back to the first available track if the requested language is not found.
    static func fetchTranscript(
        videoID: String,
        languageCode: String? = nil
    ) async throws -> TranscriptResult {
        let result = try await fetchCaptionTracks(videoID: videoID)

        guard !result.tracks.isEmpty else {
            throw TranscriptError.noCaptionsAvailable(videoID)
        }

        let track: CaptionTrack
        if let lang = languageCode,
           let match = result.tracks.first(where: { $0.languageCode == lang }) {
            track = match
        } else if languageCode != nil {
            logger.info("Language '\(languageCode!)' not found, falling back to '\(result.tracks[0].languageCode)'")
            track = result.tracks[0]
        } else {
            track = result.tracks[0]
        }

        let xml = try await fetchCaptionXML(from: track.baseURL)
        let entries = try parseCaptionXML(xml)
        return TranscriptResult(metadata: result.metadata, entries: entries, languageCode: track.languageCode)
    }

    // MARK: - Step 1: Fetch InnerTube API Key from Page

    /// Fetches the YouTube video page HTML and extracts the InnerTube API key.
    /// URL is constructed from a hardcoded template + video ID (SSRF prevention).
    private static func fetchInnertubeAPIKey(videoID: String) async throws -> String {
        let url = URL(string: "https://www.youtube.com/watch?v=\(videoID)")!
        var request = URLRequest(url: url)
        request.setValue(userAgent, forHTTPHeaderField: "User-Agent")
        request.setValue("en", forHTTPHeaderField: "Accept-Language")

        logger.debug("Fetching video page for API key: \(videoID)")

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse else {
            throw TranscriptError.networkError("Invalid response type")
        }

        guard httpResponse.statusCode == 200 else {
            throw TranscriptError.networkError("HTTP \(httpResponse.statusCode) for video \(videoID)")
        }

        guard let html = String(data: data, encoding: .utf8) else {
            throw TranscriptError.parsingError("Could not decode page HTML as UTF-8")
        }

        // Extract INNERTUBE_API_KEY from the page
        let range = NSRange(html.startIndex..., in: html)
        guard let match = apiKeyPattern.firstMatch(in: html, range: range),
              let keyRange = Range(match.range(at: 1), in: html) else {
            throw TranscriptError.parsingError("Could not find INNERTUBE_API_KEY in page")
        }

        return String(html[keyRange])
    }

    // MARK: - Step 2: Fetch Player Data via InnerTube API

    /// Fetches the full InnerTube player response for a video.
    /// Contains both videoDetails (metadata) and captions data.
    private static func fetchInnertubeData(videoID: String) async throws -> [String: Any] {
        let apiKey = try await fetchInnertubeAPIKey(videoID: videoID)

        guard let url = URL(string: "\(innertubeAPIURL)\(apiKey)") else {
            throw TranscriptError.networkError("Invalid InnerTube API URL")
        }

        let body: [String: Any] = [
            "context": [
                "client": [
                    "clientName": "ANDROID",
                    "clientVersion": androidClientVersion
                ]
            ],
            "videoId": videoID,
        ]
        let bodyData = try JSONSerialization.data(withJSONObject: body)

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.httpBody = bodyData
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(userAgent, forHTTPHeaderField: "User-Agent")

        logger.debug("Fetching InnerTube player data for \(videoID)")

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse,
              httpResponse.statusCode == 200 else {
            throw TranscriptError.networkError("InnerTube API request failed")
        }

        let parsed: Any
        do {
            parsed = try JSONSerialization.jsonObject(with: data)
        } catch {
            throw TranscriptError.parsingError(
                "Could not parse InnerTube API response: \(error.localizedDescription)"
            )
        }

        guard let json = parsed as? [String: Any] else {
            throw TranscriptError.parsingError("InnerTube API response was not a JSON object")
        }

        return json
    }

    /// Extracts video metadata from the InnerTube player response.
    private static func extractMetadata(from data: [String: Any], videoID: String) -> VideoMetadata {
        let details = data["videoDetails"] as? [String: Any]
        return VideoMetadata(
            title: details?["title"] as? String ?? "Unknown",
            channel: details?["author"] as? String ?? "Unknown",
            description: details?["shortDescription"] as? String ?? "",
            durationSeconds: Int(details?["lengthSeconds"] as? String ?? "0") ?? 0
        )
    }

    /// Extracts the captions renderer from the InnerTube player response.
    private static func extractCaptionsRenderer(
        from data: [String: Any],
        videoID: String
    ) throws -> [String: Any] {
        guard let captions = data["captions"] as? [String: Any],
              let renderer = captions["playerCaptionsTracklistRenderer"] as? [String: Any] else {
            throw TranscriptError.noCaptionsAvailable(videoID)
        }
        return renderer
    }

    /// Extracts caption tracks from the InnerTube captions JSON.
    private static func extractCaptionTracks(
        from renderer: [String: Any],
        videoID: String
    ) throws -> [CaptionTrack] {
        guard let captionTracks = renderer["captionTracks"] as? [[String: Any]] else {
            throw TranscriptError.noCaptionsAvailable(videoID)
        }

        let tracks = captionTracks.compactMap { dict -> CaptionTrack? in
            guard let baseURL = dict["baseUrl"] as? String,
                  let langCode = dict["languageCode"] as? String else {
                return nil
            }

            // The name field can be either { "simpleText": "..." } or { "runs": [{ "text": "..." }] }
            let langName: String
            if let nameDict = dict["name"] as? [String: Any] {
                if let simple = nameDict["simpleText"] as? String {
                    langName = simple
                } else if let runs = nameDict["runs"] as? [[String: Any]],
                          let firstText = runs.first?["text"] as? String {
                    langName = firstText
                } else {
                    langName = langCode
                }
            } else {
                langName = langCode
            }

            let kind = dict["kind"] as? String ?? ""
            let isAuto = kind == "asr"

            // Strip fmt=srv3 from URL if present (we want the default XML format)
            let cleanURL = baseURL.replacingOccurrences(of: "&fmt=srv3", with: "")

            return CaptionTrack(
                baseURL: cleanURL,
                languageCode: langCode,
                languageName: langName,
                isAutoGenerated: isAuto
            )
        }

        logger.debug("Found \(tracks.count) caption track(s) for \(videoID)")
        return tracks
    }

    // MARK: - Step 3: Fetch and Parse Caption XML

    /// Fetches the caption XML from a YouTube caption URL.
    private static func fetchCaptionXML(from urlString: String) async throws -> Data {
        guard let url = URL(string: urlString) else {
            throw TranscriptError.networkError("Invalid caption URL")
        }

        // SSRF hardening: only allow requests to trusted YouTube/Google domains
        guard let host = url.host?.lowercased(),
              host.hasSuffix("youtube.com") || host.hasSuffix("google.com") else {
            throw TranscriptError.networkError("Caption URL does not point to a trusted domain")
        }

        var request = URLRequest(url: url)
        request.setValue(userAgent, forHTTPHeaderField: "User-Agent")

        logger.debug("Fetching caption XML")

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse,
              httpResponse.statusCode == 200 else {
            throw TranscriptError.networkError("Failed to fetch caption XML")
        }

        guard !data.isEmpty else {
            throw TranscriptError.networkError("Caption XML response was empty")
        }

        return data
    }

    /// Parses YouTube caption XML into transcript entries.
    /// Format: `<text start="0.0" dur="2.5">caption text</text>`
    static func parseCaptionXML(_ data: Data) throws -> [TranscriptEntry] {
        let parser = CaptionXMLParser()
        let success = parser.parse(data: data)

        guard success else {
            throw TranscriptError.parsingError(parser.error ?? "Unknown XML parsing error")
        }

        guard !parser.entries.isEmpty else {
            throw TranscriptError.parsingError("Caption XML contained no text entries")
        }

        return parser.entries
    }
}

// MARK: - XML Parser Delegate

/// Delegate-based XML parser for YouTube caption format.
private final class CaptionXMLParser: NSObject, XMLParserDelegate {

    var entries: [TranscriptEntry] = []
    var error: String?

    private var currentStart: Double?
    private var currentDuration: Double?
    private var currentText: String = ""
    private var insideTextElement = false

    func parse(data: Data) -> Bool {
        let parser = XMLParser(data: data)
        parser.delegate = self
        return parser.parse()
    }

    func parser(
        _ parser: XMLParser,
        didStartElement elementName: String,
        namespaceURI: String?,
        qualifiedName: String?,
        attributes: [String: String]
    ) {
        if elementName == "text" {
            currentStart = attributes["start"].flatMap(Double.init)
            currentDuration = attributes["dur"].flatMap(Double.init)
            currentText = ""
            insideTextElement = true
        }
    }

    func parser(_ parser: XMLParser, foundCharacters string: String) {
        if insideTextElement {
            currentText += string
        }
    }

    func parser(
        _ parser: XMLParser,
        didEndElement elementName: String,
        namespaceURI: String?,
        qualifiedName: String?
    ) {
        if elementName == "text" {
            insideTextElement = false
            let start = currentStart ?? 0
            let duration = currentDuration ?? 0
            let decoded = decodeHTMLEntities(currentText)

            entries.append(TranscriptEntry(start: start, duration: duration, text: decoded))
        }
    }

    func parser(_ parser: XMLParser, parseErrorOccurred parseError: Error) {
        error = parseError.localizedDescription
    }

    /// Decodes common HTML entities found in YouTube caption XML.
    private func decodeHTMLEntities(_ text: String) -> String {
        var result = text
        let entities: [(String, String)] = [
            ("&amp;", "&"),
            ("&lt;", "<"),
            ("&gt;", ">"),
            ("&#39;", "'"),
            ("&quot;", "\""),
            ("&apos;", "'"),
            ("\n", " "),
        ]
        for (entity, replacement) in entities {
            result = result.replacingOccurrences(of: entity, with: replacement)
        }
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
