import Foundation
import Logging

struct CaptionTrack: Sendable {
    let baseURL: String
    let languageCode: String
    let languageName: String
    let isAutoGenerated: Bool
}

struct TranscriptEntry: Sendable {
    let start: Double
    let duration: Double
    let text: String
}

enum TranscriptFetcher {

    private static let logger = Logger(label: "yt_transcript_mcp.fetcher")

    private static let userAgent =
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

    // InnerTube API endpoint (Android client avoids PO token requirement)
    private static let innertubeAPIURL = "https://www.youtube.com/youtubei/v1/player?key="

    // MARK: - Public API

    /// Fetches available caption tracks for a video.
    static func fetchCaptionTracks(videoID: String) async throws -> [CaptionTrack] {
        let captionsJSON = try await fetchCaptionsJSON(videoID: videoID)
        let tracks = try extractCaptionTracks(from: captionsJSON, videoID: videoID)
        return tracks
    }

    /// Fetches the transcript for a video, optionally in a specific language.
    /// Falls back to the first available track if the requested language is not found.
    static func fetchTranscript(
        videoID: String,
        languageCode: String? = nil
    ) async throws -> [TranscriptEntry] {
        let tracks = try await fetchCaptionTracks(videoID: videoID)

        guard !tracks.isEmpty else {
            throw TranscriptError.noCaptionsAvailable(videoID)
        }

        let track: CaptionTrack
        if let lang = languageCode,
           let match = tracks.first(where: { $0.languageCode == lang }) {
            track = match
        } else if languageCode != nil {
            logger.info("Language '\(languageCode!)' not found, falling back to '\(tracks[0].languageCode)'")
            track = tracks[0]
        } else {
            track = tracks[0]
        }

        let xml = try await fetchCaptionXML(from: track.baseURL)
        let entries = try parseCaptionXML(xml)
        return entries
    }

    // MARK: - Step 1: Fetch InnerTube API Key from Page

    /// Fetches the YouTube video page HTML and extracts the InnerTube API key.
    /// URL is constructed from a hardcoded template + video ID (SSRF prevention).
    private static func fetchInnertubeAPIKey(videoID: String) async throws -> String {
        let url = URL(string: "https://www.youtube.com/watch?v=\(videoID)")!
        var request = URLRequest(url: url)
        request.setValue(userAgent, forHTTPHeaderField: "User-Agent")
        request.setValue("en", forHTTPHeaderField: "Accept-Language")

        logger.debug("Fetching video page for API key: \(videoID)")

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse else {
            throw TranscriptError.networkError("Invalid response type")
        }

        guard httpResponse.statusCode == 200 else {
            throw TranscriptError.networkError("HTTP \(httpResponse.statusCode) for video \(videoID)")
        }

        guard let html = String(data: data, encoding: .utf8) else {
            throw TranscriptError.parsingError("Could not decode page HTML as UTF-8")
        }

        // Extract INNERTUBE_API_KEY from the page
        let pattern = try! NSRegularExpression(pattern: #""INNERTUBE_API_KEY":\s*"([a-zA-Z0-9_-]+)""#)
        let range = NSRange(html.startIndex..., in: html)
        guard let match = pattern.firstMatch(in: html, range: range),
              let keyRange = Range(match.range(at: 1), in: html) else {
            throw TranscriptError.parsingError("Could not find INNERTUBE_API_KEY in page")
        }

        return String(html[keyRange])
    }

    // MARK: - Step 2: Fetch Captions via InnerTube API

    /// Uses the InnerTube API to get caption track data for a video.
    /// This returns caption URLs that work without a PO token.
    private static func fetchCaptionsJSON(videoID: String) async throws -> [String: Any] {
        let apiKey = try await fetchInnertubeAPIKey(videoID: videoID)

        guard let url = URL(string: "\(innertubeAPIURL)\(apiKey)") else {
            throw TranscriptError.networkError("Invalid InnerTube API URL")
        }

        let body: [String: Any] = [
            "context": [
                "client": [
                    "clientName": "ANDROID",
                    "clientVersion": "20.10.38"
                ]
            ],
            "videoId": videoID,
        ]
        let bodyData = try JSONSerialization.data(withJSONObject: body)

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.httpBody = bodyData
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(userAgent, forHTTPHeaderField: "User-Agent")

        logger.debug("Fetching InnerTube player data for \(videoID)")

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse,
              httpResponse.statusCode == 200 else {
            throw TranscriptError.networkError("InnerTube API request failed")
        }

        guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw TranscriptError.parsingError("Could not parse InnerTube API response")
        }

        // Navigate to captions > playerCaptionsTracklistRenderer
        guard let captions = json["captions"] as? [String: Any],
              let renderer = captions["playerCaptionsTracklistRenderer"] as? [String: Any] else {
            throw TranscriptError.noCaptionsAvailable(videoID)
        }

        return renderer
    }

    /// Extracts caption tracks from the InnerTube captions JSON.
    private static func extractCaptionTracks(
        from renderer: [String: Any],
        videoID: String
    ) throws -> [CaptionTrack] {
        guard let captionTracks = renderer["captionTracks"] as? [[String: Any]] else {
            throw TranscriptError.noCaptionsAvailable(videoID)
        }

        let tracks = captionTracks.compactMap { dict -> CaptionTrack? in
            guard let baseURL = dict["baseUrl"] as? String,
                  let langCode = dict["languageCode"] as? String else {
                return nil
            }

            // The name field can be either { "simpleText": "..." } or { "runs": [{ "text": "..." }] }
            let langName: String
            if let nameDict = dict["name"] as? [String: Any] {
                if let simple = nameDict["simpleText"] as? String {
                    langName = simple
                } else if let runs = nameDict["runs"] as? [[String: Any]],
                          let firstText = runs.first?["text"] as? String {
                    langName = firstText
                } else {
                    langName = langCode
                }
            } else {
                langName = langCode
            }

            let kind = dict["kind"] as? String ?? ""
            let isAuto = kind == "asr"

            // Strip fmt=srv3 from URL if present (we want the default XML format)
            let cleanURL = baseURL.replacingOccurrences(of: "&fmt=srv3", with: "")

            return CaptionTrack(
                baseURL: cleanURL,
                languageCode: langCode,
                languageName: langName,
                isAutoGenerated: isAuto
            )
        }

        logger.debug("Found \(tracks.count) caption track(s) for \(videoID)")
        return tracks
    }

    // MARK: - Step 3: Fetch and Parse Caption XML

    /// Fetches the caption XML from a YouTube caption URL.
    private static func fetchCaptionXML(from urlString: String) async throws -> Data {
        guard let url = URL(string: urlString) else {
            throw TranscriptError.networkError("Invalid caption URL")
        }

        var request = URLRequest(url: url)
        request.setValue(userAgent, forHTTPHeaderField: "User-Agent")

        logger.debug("Fetching caption XML")

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse,
              httpResponse.statusCode == 200 else {
            throw TranscriptError.networkError("Failed to fetch caption XML")
        }

        guard !data.isEmpty else {
            throw TranscriptError.networkError("Caption XML response was empty")
        }

        return data
    }

    /// Parses YouTube caption XML into transcript entries.
    /// Format: `<text start="0.0" dur="2.5">caption text</text>`
    private static func parseCaptionXML(_ data: Data) throws -> [TranscriptEntry] {
        let parser = CaptionXMLParser()
        let success = parser.parse(data: data)

        guard success else {
            throw TranscriptError.parsingError(parser.error ?? "Unknown XML parsing error")
        }

        guard !parser.entries.isEmpty else {
            throw TranscriptError.parsingError("Caption XML contained no text entries")
        }

        return parser.entries
    }
}

// MARK: - XML Parser Delegate

/// Delegate-based XML parser for YouTube caption format.
private final class CaptionXMLParser: NSObject, XMLParserDelegate, @unchecked Sendable {

    var entries: [TranscriptEntry] = []
    var error: String?

    private var currentStart: Double?
    private var currentDuration: Double?
    private var currentText: String = ""
    private var insideTextElement = false

    func parse(data: Data) -> Bool {
        let parser = XMLParser(data: data)
        parser.delegate = self
        return parser.parse()
    }

    func parser(
        _ parser: XMLParser,
        didStartElement elementName: String,
        namespaceURI: String?,
        qualifiedName: String?,
        attributes: [String: String]
    ) {
        if elementName == "text" {
            currentStart = attributes["start"].flatMap(Double.init)
            currentDuration = attributes["dur"].flatMap(Double.init)
            currentText = ""
            insideTextElement = true
        }
    }

    func parser(_ parser: XMLParser, foundCharacters string: String) {
        if insideTextElement {
            currentText += string
        }
    }

    func parser(
        _ parser: XMLParser,
        didEndElement elementName: String,
        namespaceURI: String?,
        qualifiedName: String?
    ) {
        if elementName == "text" {
            insideTextElement = false
            let start = currentStart ?? 0
            let duration = currentDuration ?? 0
            let decoded = decodeHTMLEntities(currentText)

            entries.append(TranscriptEntry(start: start, duration: duration, text: decoded))
        }
    }

    func parser(_ parser: XMLParser, parseErrorOccurred parseError: Error) {
        error = parseError.localizedDescription
    }

    /// Decodes common HTML entities found in YouTube caption XML.
    private func decodeHTMLEntities(_ text: String) -> String {
        var result = text
        let entities: [(String, String)] = [
            ("&amp;", "&"),
            ("&lt;", "<"),
            ("&gt;", ">"),
            ("&#39;", "'"),
            ("&quot;", "\""),
            ("&apos;", "'"),
            ("\n", " "),
        ]
        for (entity, replacement) in entities {
            result = result.replacingOccurrences(of: entity, with: replacement)
        }
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
